name: evital
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  hive: ^2.2.3
  path_provider: ^2.1.3

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.4

flutter: 
  uses-material-design: true

